# Generated by Django 3.2.4 on 2021-06-17 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('masterkey', models.CharField(max_length=40, unique=True)),
                ('quota', models.PositiveIntegerField(default=1000)),
                ('is_active', models.BooleanField(default='True')),
                ('is_admin', models.BooleanField(default='False')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DownloadTokens',
            fields=[
                ('location', models.CharField(max_length=150, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storageInterface.bucket')),
            ],
        ),
        migrations.CreateModel(
            name='AppTokens',
            fields=[
                ('token', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storageInterface.bucket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
